export const DEFAULT_FAILED_ATTEMPTS_BAN = 3;
export const MAX_SEND_EMAIL_RECORDS_PER_MINUTE = 5;

export const INJECTION_TOKEN = {
  AUDIT_SERVICE: Symbol.for('AUDIT_SERVICE'),
  HTTP_SERVICE: Symbol.for('HTTP_SERVICE'),
  REDIS_SERVICE: Symbol.for('REDIS_SERVICE'),
  SYNC_TASK_QUEUE: Symbol.for('SYNC_TASK_QUEUE'),
  OPIK_SERVICE: Symbol.for('OPIK_SERVICE'),
  MAIL_TRANSPORTER: Symbol.for('MAIL_TRANSPORTER'),
  CLOUDINARY_SERVICE: Symbol.for('CLOUDINARY_SERVICE'),
  GROQ_SERVICE: Symbol.for('GROQ_SERVICE'),
};

export const ERR_CODE = {
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS'.toLowerCase(),
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'.toLowerCase(),
  NOT_FOUND: 'NOT_FOUND'.toLowerCase(),
  BAD_REQUEST: 'BAD_REQUEST'.toLowerCase(),
  ALREADY_EXISTS: 'ALREADY_EXISTS'.toLowerCase(),
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY'.toLowerCase(),
  FORBIDDEN: 'FORBIDDEN'.toLowerCase(),
  UNAUTHORIZED: 'UNAUTHORIZED'.toLowerCase(),
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS'.toLowerCase(),
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS'.toLowerCase(),
  USER_NOT_FOUND: 'USER_NOT_FOUND'.toLowerCase(),
  ACCOUNT_IS_NOT_ACTIVE: 'ACCOUNT_IS_NOT_ACTIVE'.toLowerCase(),
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED'.toLowerCase(),
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT'.toLowerCase(),
  OTP_ALREADY_SENT: 'OTP_ALREADY_SENT'.toLowerCase(),
  INVALID_OTP: 'INVALID_OTP'.toLowerCase(),
  PASSWORD_OR_USERNAME_INCORRECT:
    'PASSWORD_OR_USERNAME_INCORRECT'.toLowerCase(),
  PASSWORD_CONFIRMATION_MISMATCH:
    'PASSWORD_CONFIRMATION_MISMATCH'.toLowerCase(),
  PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD'.toLowerCase(),
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE'.toLowerCase(),
  RISK_ASSESSMENT_FAILED: 'RISK_ASSESSMENT_FAILED'.toLowerCase(),
  SYSTEM_BUSY: 'SYSTEM_BUSY'.toLowerCase(),
  HEALTH_RECORD_NOT_FOUND: 'HEALTH_RECORD_NOT_FOUND'.toLowerCase(),
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND'.toLowerCase(),
};

export const APP_ACTION = {
  BAN_TOO_MANY_FAILED_ATTEMPTS: 'BAN_TOO_MANY_FAILED_ATTEMPTS'.toLowerCase(),
  API_CALL: 'API_CALL'.toLowerCase(),
  HANDLE_EXCEPTION: 'HANDLE_EXCEPTION'.toLowerCase(),
  REGISTER: 'REGISTER'.toLowerCase(),
  LOGIN: 'LOGIN'.toLowerCase(),
  FORGOT_PASSWORD: 'FORGOT_PASSWORD'.toLowerCase(),
  RESET_PASSWORD: 'RESET_PASSWORD'.toLowerCase(),
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'.toLowerCase(),
  SOCIAL_LOGIN: 'SOCIAL_LOGIN'.toLowerCase(),
  SEND_EMAIL: 'SEND_EMAIL'.toLowerCase(),
  SEND_TO_PARTNER: 'SEND_TO_PARTNER'.toLowerCase(),
};

export enum VERIFY_OTP_ACTION {
  REGISTER = 'register',
}

export enum SOCIAL_PROVIDER {
  GOOGLE = 'google',
}

export enum ENV_KEY {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',

  APP_NAME = 'APP_NAME',
  APP_PUBLIC_URL = 'APP_PUBLIC_URL',

  AUDIT_WEBHOOK_URL = 'AUDIT_WEBHOOK_URL',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  SERVICE_NAME = 'SERVICE_NAME',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

  ENCRYPTION_KEY = 'ENCRYPTION_KEY',

  OPIK_API_KEY = 'OPIK_API_KEY',
  OPIK_WORKSPACE = 'OPIK_WORKSPACE',
  OPIK_PROJECT = 'OPIK_PROJECT',

  SMTP_HOST = 'SMTP_HOST',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_SECURE = 'SMTP_SECURE',
  SMTP_USERNAME = 'SMTP_USERNAME',
  SMTP_PASSWORD = 'SMTP_PASSWORD',

  ADMIN_EMAILS = 'ADMIN_EMAILS',

  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  GROQ_API_KEY = 'GROQ_API_KEY',

  PARTNER_FOOD_RECOMMENDATION_URL = 'PARTNER_FOOD_RECOMMENDATION_URL',
}

export enum METADATA_KEY {
  MAX_CONCURRENCY_CALL = 'max_concurrency_call',
  RATE_LIMITING = 'rate_limiting',
  USER_ID_EXTRACTOR = 'user_id_extractor',
  MAX_ATTEMPTS_ALLOWED = 'max_attempts_allowed',
}

export const DEFAULT_MAX_CONCURRENT_CALL = 1;

export enum HEADER_KEY {
  CONTENT_TYPE = 'Content-Type',
  CAPTCHA_TOKEN = 'X-Captcha-Token',
  LOG_ID = 'X-Log-ID',
  SESSION_TOKEN = 'X-Session-Token',
  ACCESS_KEY_ID = 'X-Access-Key-ID',
  ACCESS_KEY_SECRET = 'X-Access-Key-Secret',
  PARTNER_ACCESS_SECRET = 'X-Partner-Access-Secret',
}

export enum ENTITY_STATUS {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  SUSPENDED = 'suspended',
}

export enum EMAIL_TEMPLATE {
  EMAIL_VERIFICATION = 'email-verification',
  EMAIL_RESET_PASSWORD = 'reset-password',
}

export enum CLOUDINARY_FOLDER {
  SCAN_HEALTH_RECORD = 'scan-health-record',
}

export enum AGENT_CHAT_MESSAGE_FORMAT {
  MARKDOWN = 'markdown',
}

export enum AGENT_CHAT_MESSAGE_ROLE {
  USER = 'user',
  ASSISTANT = 'assistant',
  SYSTEM = 'system',
}

export enum WEIGHT_UNIT {
  KG = 'kg',
  LB = 'lb',
}

export enum HEIGHT_UNIT {
  CM = 'cm',
  IN = 'in',
}

export enum EXERCISES_GROUP {
  CARDIO = 'cardio',
  LIGHT_RECOVERY = 'light_recovery',
  FLEXIBILITY = 'flexibility',
  STRENGTH = 'strength',
  SPORTS = 'sports',
  MIXED = 'mixed',
}

export enum EXERCISES_INTENSITY {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
}

export enum EXERCISES_FREQUENCY {
  OCCASIONAL = 'occasional',
  REGULAR = 'regular',
  ACTIVE = 'active',
  VERY_ACTIVE = 'very_active',
}
